config/routes.rb
Rails.application.routes.draw do
  resources :kwales
  resources :nairobis
  resources :nyanzas
  resources :westerns
  resources :southrifts
  resources :northrifts
  resources :centrals
  resources :lowereasterns
  resources :uppereasterns
  resources :northeasterns
  resources :packholidays
  resources :patrolleaderscourses
  resources :badges
  resources :sessions, only: [:create]
  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"
  resources :users
  get "register", to: "users#new"

  resources :investitures
  resources :coasts
  resources :mombasas

  root "sessions#index"
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/central.rb
class Central < ApplicationRecord
end

app/models/coast.rb
class Coast < ApplicationRecord
end

app/models/investiture.rb
class Investiture < ApplicationRecord
end

app/models/kwale.rb
class Kwale < ApplicationRecord
before_create :create_total
  before_save :create_total

  validates :sub_county, presence: true
  validates :investiture_sungura, presence: true
  validates :investiture_chipukizi, presence: true
  validates :investiture_mwamba, presence: true
  validates :investiture_jasiri, presence: true

  default_scope {order('kwales.created_at ASC')}

  def create_total
    self.total = self.investiture_sungura + self.investiture_chipukizi + self.investiture_mwamba + self.investiture_jasiri
  end
end

app/models/lowereastern.rb
class Lowereastern < ApplicationRecord
end

app/models/mombasa.rb
class Mombasa < ApplicationRecord
  before_create :create_total
  before_save :create_total

  validates :sub_county, presence: true
  validates :investiture_sungura, presence: true
  validates :investiture_chipukizi, presence: true
  validates :investiture_mwamba, presence: true
  validates :investiture_jasiri, presence: true

  default_scope {order('mombasas.created_at ASC')}

  def create_total
    self.total = self.investiture_sungura + self.investiture_chipukizi + self.investiture_mwamba + self.investiture_jasiri
  end
end

app/models/nairobi.rb
class Nairobi < ApplicationRecord
end

app/models/northeastern.rb
class Northeastern < ApplicationRecord
end

app/models/northrift.rb
class Northrift < ApplicationRecord
end

app/models/nyanza.rb
class Nyanza < ApplicationRecord
end

app/models/packholiday.rb
class Packholiday < ApplicationRecord
end

app/models/southrift.rb
class Southrift < ApplicationRecord
end

app/models/uppereastern.rb
class Uppereastern < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/models/western.rb
class Western < ApplicationRecord
end

app/controllers/southrifts_controller.rb
class SouthriftsController < ApplicationController
  before_action :set_southrift, only: %i[ show edit update destroy ]

  # GET /southrifts or /southrifts.json
  def index
    @southrifts = Southrift.all
  end

  # GET /southrifts/1 or /southrifts/1.json
  def show
  end

  # GET /southrifts/new
  def new
    @southrift = Southrift.new
  end

  # GET /southrifts/1/edit
  def edit
  end

  # POST /southrifts or /southrifts.json
  def create
    @southrift = Southrift.new(southrift_params)

    respond_to do |format|
      if @southrift.save
        format.html { redirect_to southrift_url(@southrift), notice: "Southrift was successfully created." }
        format.json { render :show, status: :created, location: @southrift }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @southrift.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /southrifts/1 or /southrifts/1.json
  def update
    respond_to do |format|
      if @southrift.update(southrift_params)
        format.html { redirect_to southrift_url(@southrift), notice: "Southrift was successfully updated." }
        format.json { render :show, status: :ok, location: @southrift }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @southrift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /southrifts/1 or /southrifts/1.json
  def destroy
    @southrift.destroy

    respond_to do |format|
      format.html { redirect_to southrifts_url, notice: "Southrift was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_southrift
      @southrift = Southrift.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def southrift_params
      params.fetch(:southrift, {})
    end
end

app/helpers/alert_helper.rb
module AlertHelper
  def build_alert_classes(alert_type)
    classes = 'alert alert-dismissable '
    case alert_type.to_sym 
    when :alert, :danger, :error, :validation_errors
      classes += 'alert-danger'
    when :warning, :todo
      classes += 'alert-warning'
    when :notice, :success
      classes += 'alert-success'
    else 
      classes += 'alert-info'
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/coasts_helper.rb
module CoastsHelper
end

app/helpers/kwales_helper.rb
module KwalesHelper
end

app/helpers/southrifts_helper.rb
module SouthriftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/southrifts/_form.html.erb
<%= form_with(model: southrift) do |form| %>
  <% if southrift.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(southrift.errors.count, "error") %> prohibited this southrift from being saved:</h2>

      <ul>
        <% southrift.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/southrifts/_southrift.html.erb
<div id="<%= dom_id southrift %>">
</div>

app/views/southrifts/edit.html.erb
<h1>Editing southrift</h1>

<%= render "form", southrift: @southrift %>

<br>

<div>
  <%= link_to "Show this southrift", @southrift %> |
  <%= link_to "Back to southrifts", southrifts_path %>
</div>

app/views/southrifts/index.html.erb
<section style="min-height: calc(90vh - 40px);padding: 180px 40px 100px 40px;">
  <div style="background-color: rgba(174, 182, 191, 0.4);border-radius: 10px;width: 95%;margin: auto;padding: 20px;">
    <div style="padding: 10px;">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: build_alert_classes(type) %>
      <% end %>
    </div>

    <div style="padding: 0 40px 40px 40px;">
      <h3>COUNTY</h3>
      <div class="row">
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/mombasas'">
          <h1>Nakuru</h1>
          <i class="fa-solid fa-map-location"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='#'">
          <h1>Narok</h1>
          <i class="fa-solid fa-map-location"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='#'">
          <h1>Kajiado</h1>
          <i class="fa-solid fa-map-location"></i>
        </div>
      </div>
      <div class="row">
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='#'">
          <h1>Kericho</h1>
          <i class="fa-solid fa-map-location"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='#'">
          <h1>Bomet</h1>
          <i class="fa-solid fa-map-location"></i>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/southrifts/new.html.erb
<h1>New southrift</h1>

<%= render "form", southrift: @southrift %>

<br>

<div>
  <%= link_to "Back to southrifts", southrifts_path %>
</div>

app/views/southrifts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @southrift %>

<div>
  <%= link_to "Edit this southrift", edit_southrift_path(@southrift) %> |
  <%= link_to "Back to southrifts", southrifts_path %>

  <%= button_to "Destroy this southrift", @southrift, method: :delete %>
</div>