config/routes.rb
Rails.application.routes.draw do
  resources :kwales
  resources :nairobis
  resources :nyanzas
  resources :westerns
  resources :southrifts
  resources :northrifts
  resources :centrals
  resources :lowereasterns
  resources :uppereasterns
  resources :northeasterns
  resources :packholidays
  resources :patrolleaderscourses
  resources :badges
  resources :sessions, only: [:create]
  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"
  resources :users
  get "register", to: "users#new"

  resources :investitures
  resources :coasts
  resources :mombasas

  root "sessions#index"
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/central.rb
class Central < ApplicationRecord
end

app/models/coast.rb
class Coast < ApplicationRecord
end

app/models/investiture.rb
class Investiture < ApplicationRecord
end

app/models/kwale.rb
class Kwale < ApplicationRecord
before_create :create_total
  before_save :create_total

  validates :sub_county, presence: true
  validates :investiture_sungura, presence: true
  validates :investiture_chipukizi, presence: true
  validates :investiture_mwamba, presence: true
  validates :investiture_jasiri, presence: true

  default_scope {order('kwales.created_at ASC')}

  def create_total
    self.total = self.investiture_sungura + self.investiture_chipukizi + self.investiture_mwamba + self.investiture_jasiri
  end
end

app/models/lowereastern.rb
class Lowereastern < ApplicationRecord
end

app/models/mombasa.rb
class Mombasa < ApplicationRecord
  before_create :create_total
  before_save :create_total

  validates :sub_county, presence: true
  validates :investiture_sungura, presence: true
  validates :investiture_chipukizi, presence: true
  validates :investiture_mwamba, presence: true
  validates :investiture_jasiri, presence: true

  default_scope {order('mombasas.created_at ASC')}

  def create_total
    self.total = self.investiture_sungura + self.investiture_chipukizi + self.investiture_mwamba + self.investiture_jasiri
  end
end

app/models/nairobi.rb
class Nairobi < ApplicationRecord
end

app/models/northeastern.rb
class Northeastern < ApplicationRecord
end

app/models/northrift.rb
class Northrift < ApplicationRecord
end

app/models/nyanza.rb
class Nyanza < ApplicationRecord
end

app/models/packholiday.rb
class Packholiday < ApplicationRecord
end

app/models/southrift.rb
class Southrift < ApplicationRecord
end

app/models/uppereastern.rb
class Uppereastern < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/models/western.rb
class Western < ApplicationRecord
end

app/controllers/badges_controller.rb
class BadgesController < ApplicationController
  before_action :set_badge, only: %i[ show edit update destroy ]

  # GET /badges or /badges.json
  def index
    @badges = Badge.all
  end

  # GET /badges/1 or /badges/1.json
  def show
  end

  # GET /badges/new
  def new
    @badge = Badge.new
  end

  # GET /badges/1/edit
  def edit
  end

  # POST /badges or /badges.json
  def create
    @badge = Badge.new(badge_params)

    respond_to do |format|
      if @badge.save
        format.html { redirect_to badge_url(@badge), notice: "Badge was successfully created." }
        format.json { render :show, status: :created, location: @badge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /badges/1 or /badges/1.json
  def update
    respond_to do |format|
      if @badge.update(badge_params)
        format.html { redirect_to badge_url(@badge), notice: "Badge was successfully updated." }
        format.json { render :show, status: :ok, location: @badge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @badge.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /badges/1 or /badges/1.json
  def destroy
    @badge.destroy

    respond_to do |format|
      format.html { redirect_to badges_url, notice: "Badge was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_badge
      @badge = Badge.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def badge_params
      params.fetch(:badge, {})
    end
end

app/helpers/alert_helper.rb
module AlertHelper
  def build_alert_classes(alert_type)
    classes = 'alert alert-dismissable '
    case alert_type.to_sym 
    when :alert, :danger, :error, :validation_errors
      classes += 'alert-danger'
    when :warning, :todo
      classes += 'alert-warning'
    when :notice, :success
      classes += 'alert-success'
    else 
      classes += 'alert-info'
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/coasts_helper.rb
module CoastsHelper
end

app/helpers/kwales_helper.rb
module KwalesHelper
end

app/helpers/nyanzas_helper.rb
module NyanzasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/badges/_badge.html.erb
<div id="<%= dom_id badge %>">
</div>

app/views/badges/_form.html.erb
<%= form_with(model: badge) do |form| %>
  <% if badge.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(badge.errors.count, "error") %> prohibited this badge from being saved:</h2>

      <ul>
        <% badge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/badges/edit.html.erb
<h1>Editing badge</h1>

<%= render "form", badge: @badge %>

<br>

<div>
  <%= link_to "Show this badge", @badge %> |
  <%= link_to "Back to badges", badges_path %>
</div>

app/views/badges/index.html.erb
<section style="min-height: calc(90vh - 40px);padding: 180px 40px 100px 40px;">
  <div style="background-color: rgba(174, 182, 191, 0.4);border-radius: 10px;width: 95%;margin: auto;padding: 20px;">
    <div style="padding: 10px;">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: build_alert_classes(type) %>
      <% end %>
    </div>

    <div style="padding: 0 40px 40px 40px;">
      <h3>REGIONS</h3>
      <div class="row">
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/coasts'">
          <h1>Coast</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/northeasterns'">
          <h1>North Eastern</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/uppereasterns'">
          <h1>Upper Eastern</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
      </div>
      <div class="row">
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/lowereasterns'">
          <h1>Lower Eastern</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/centrals'">
          <h1>Central</h1>
          <i class="fa-solid fa-location-dot"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/northrifts'">
          <h1>North Rift</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
      </div>
      <div class="row">
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/southrifts'">
          <h1>South Rift</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/westerns'">
          <h1>Western</h1>
          <i class="fa-solid fa-location-dot"></i>
        </div>
        <div class="col home-widget bottom-margin" type="button" onclick="location.href='/nyanzas'">
          <h1>Nyanza</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
      </div>
      <div class="row">
        <div class="col-12 home-widget bottom-margin" type="button" onclick="location.href='/nairobis'">
          <h1>Nairobi</h1>
        <i class="fa-solid fa-location-dot"></i>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/badges/new.html.erb
<h1>New badge</h1>

<%= render "form", badge: @badge %>

<br>

<div>
  <%= link_to "Back to badges", badges_path %>
</div>

app/views/badges/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @badge %>

<div>
  <%= link_to "Edit this badge", edit_badge_path(@badge) %> |
  <%= link_to "Back to badges", badges_path %>

  <%= button_to "Destroy this badge", @badge, method: :delete %>
</div>