config/routes.rb
Rails.application.routes.draw do
  resources :kwales
  resources :nairobis
  resources :nyanzas
  resources :westerns
  resources :southrifts
  resources :northrifts
  resources :centrals
  resources :lowereasterns
  resources :uppereasterns
  resources :northeasterns
  resources :packholidays
  resources :patrolleaderscourses
  resources :badges
  resources :sessions, only: [:create]
  get "login", to: "sessions#new"
  get "logout", to: "sessions#destroy"
  resources :users
  get "register", to: "users#new"

  resources :investitures
  resources :coasts
  resources :mombasas

  root "sessions#index"
end

app/models/badge.rb
class Badge < ApplicationRecord
end

app/models/central.rb
class Central < ApplicationRecord
end

app/models/coast.rb
class Coast < ApplicationRecord
end

app/models/investiture.rb
class Investiture < ApplicationRecord
end

app/models/kwale.rb
class Kwale < ApplicationRecord
before_create :create_total
  before_save :create_total

  validates :sub_county, presence: true
  validates :investiture_sungura, presence: true
  validates :investiture_chipukizi, presence: true
  validates :investiture_mwamba, presence: true
  validates :investiture_jasiri, presence: true

  default_scope {order('kwales.created_at ASC')}

  def create_total
    self.total = self.investiture_sungura + self.investiture_chipukizi + self.investiture_mwamba + self.investiture_jasiri
  end
end

app/models/lowereastern.rb
class Lowereastern < ApplicationRecord
end

app/models/mombasa.rb
class Mombasa < ApplicationRecord
  before_create :create_total
  before_save :create_total

  validates :sub_county, presence: true
  validates :investiture_sungura, presence: true
  validates :investiture_chipukizi, presence: true
  validates :investiture_mwamba, presence: true
  validates :investiture_jasiri, presence: true

  default_scope {order('mombasas.created_at ASC')}

  def create_total
    self.total = self.investiture_sungura + self.investiture_chipukizi + self.investiture_mwamba + self.investiture_jasiri
  end
end

app/models/nairobi.rb
class Nairobi < ApplicationRecord
end

app/models/northeastern.rb
class Northeastern < ApplicationRecord
end

app/models/northrift.rb
class Northrift < ApplicationRecord
end

app/models/nyanza.rb
class Nyanza < ApplicationRecord
end

app/models/packholiday.rb
class Packholiday < ApplicationRecord
end

app/models/southrift.rb
class Southrift < ApplicationRecord
end

app/models/uppereastern.rb
class Uppereastern < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, presence: true, uniqueness: true, format: {with: URI::MailTo::EMAIL_REGEXP}
end

app/models/western.rb
class Western < ApplicationRecord
end

app/controllers/mombasas_controller.rb
class MombasasController < ApplicationController
  def index
    @mombasas = Mombasa.all
  end

  def edit
    @mombasa = Mombasa.find(params[:id])
  end

  def create
    @mombasa = Mombasa.new(mombasa_params)

    if @mombasa.save
      flash[:notice] = "Record Created"
      redirect_to "/mombasas"
    else
      flash[:alert] = @mombasa.errors.full_messages.join(', ') 
      redirect_to "/mombasas"
    end
  end

  def update
    @mombasa = Mombasa.find(params[:id])
    @mombasa.update(mombasa_params)
    flash[:success] = "Record Updated Successfully"
    redirect_to '/mombasas'
  end

  def destroy
    @mombasa = Mombasa.find(params[:id])
    @mombasa.destroy
    flash[:success] = "Record Deleted"
    redirect_to '/mombasas'
  end

  private

  def mombasa_params
    params.require(:mombasa).permit(:sub_county, :investiture_sungura, :investiture_chipukizi, :investiture_mwamba, :investiture_jasiri, :total)
  end
end

app/helpers/alert_helper.rb
module AlertHelper
  def build_alert_classes(alert_type)
    classes = 'alert alert-dismissable '
    case alert_type.to_sym 
    when :alert, :danger, :error, :validation_errors
      classes += 'alert-danger'
    when :warning, :todo
      classes += 'alert-warning'
    when :notice, :success
      classes += 'alert-success'
    else 
      classes += 'alert-info'
    end
  end
end

app/helpers/badges_helper.rb
module BadgesHelper
end

app/helpers/coasts_helper.rb
module CoastsHelper
end

app/helpers/kwales_helper.rb
module KwalesHelper
end

app/helpers/mombasas_helper.rb
module MombasasHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/mombasas/edit.html.erb
<div class="limiter">
  <div class="container-login100" style="padding-top: 160px;padding-bottom: 60px;">
    <div class="wrap-login100">
      <div class="login100-form-title" style="background-image: url(/assets/login-image.png);">
        <span class="login100-form-title-1">
          <b>Edit Record</b>
        </span>
      </div>

      <div style="padding: 10px;">
        <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: build_alert_classes(type) %>
        <% end %>
      </div>

      <%= form_for @mombasa, url: {action: "update"}, html: {class: "login100-form validate-form"} do |f| %>
        <div class="row" style="width: 100%;">
          <div class="wrap-input100 validate-input m-b-26" data-validate="Sub County is required" style="margin-bottom: 20px !important;">
            <span class="label-input100">Sub County:</span>
            <%= f.text_field :sub_county, class: 'input100', value: @mombasa.sub_county %>
            <span class="focus-input100"></span>
          </div>

          <div class="wrap-input100 validate-input m-b-26" data-validate="Sungura is required" style="margin-bottom: 20px !important;">
            <span class="label-input100">Sungura:</span>
            <%= f.text_field :investiture_sungura, class: 'input100', value: @mombasa.investiture_sungura %>
            <span class="focus-input100"></span>
          </div>

          <div class="wrap-input100 validate-input m-b-26" data-validate="Chipukizi is required" style="margin-bottom: 20px !important;">
            <span class="label-input100">Chipukizi:</span>
            <%= f.text_field :investiture_chipukizi, class: 'input100', value: @mombasa.investiture_chipukizi %>
            <span class="focus-input100"></span>
          </div>

          <div class="wrap-input100 validate-input m-b-26" data-validate="Mwamba is required" style="margin-bottom: 20px !important;">
            <span class="label-input100">Mwamba:</span>
            <%= f.text_field :investiture_mwamba, class: 'input100', value: @mombasa.investiture_mwamba %>
            <span class="focus-input100"></span>
          </div>

          <div class="wrap-input100 validate-input m-b-26" data-validate="Jasiri is required" style="margin-bottom: 20px !important;">
            <span class="label-input100">Jasiri:</span>
            <%= f.text_field :investiture_jasiri, class: 'input100', value: @mombasa.investiture_jasiri %>
            <span class="focus-input100"></span>
          </div>


          <div class="container-login100-form-btn" style="margin: 40px 0 40px 0 !important;">
            <button type="submit" class="login100-form-btn">Edit!</button>
          </div>
        </div>
      <% end %>

    </div>
  </div>
</div>

app/views/mombasas/index.html.erb
<section style="min-height: calc(90vh - 40px);padding: 180px 40px 100px 40px;">
  <div style="background-color: rgba(174, 182, 191, 0.4);border-radius: 10px;width: 95%;margin: auto;padding: 20px 20px 80px 20px;">

    <div style="padding: 50px 0 40px 40px;text-align: left;">
      <a class="record-button1" type="button" onclick="location.href='/mombasas/new'">
        <i class="fa-solid fa-plus">&ensp;</i>
        <span>Add Record</span>
      </a>
    </div>

    <div style="padding: 10px;">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: build_alert_classes(type) %>
      <% end %>
    </div>

    <!-- Table To Show In Website -->
    <div style="padding: 0 40px 20px 40px;">
      <h2 style="padding-bottom: 20px;">SUB-COUNTY INVESTITURE</h2>
      
      <div class="table-responsive">
        <table class="table table-hover">
          <tr style="font-size: 1.5rem;">
            <th>SUB-COUNTY</th>
            <th colspan="4">INVESTITURE</th>
            <th>TOTAL</th>
            <th>Edit</th>
            <th>Delete</th>
          </tr>
          <tr style="font-size: 1.4rem;">
            <td></td>
            <td><b>Sungura</b></td>
            <td><b>Chipukizi</b></td>
            <td><b>Mwamba</b></td>
            <td><b>Jasiri</b></td>
            <td></td>
            <td></td>
            <td></td>
          </tr>

          <% @mombasas.each do |mombasa| %>
            <tr style="font-size: 1.2rem;">
              <td><b><%= mombasa.sub_county %></b></td>
              <td><%= mombasa.investiture_sungura %></td>
              <td><%= mombasa.investiture_chipukizi %></td>
              <td><%= mombasa.investiture_mwamba %></td>
              <td><%= mombasa.investiture_jasiri %></td>
              <td><b><%= mombasa.total %></b></td>
              <td><b><%= link_to '', edit_mombasa_path(mombasa), :class => "fas fa-edit" %></b></td>
              <td>
                <b>
                  <%= button_to '', mombasa_path(mombasa), method: :delete, data: {confirm: 'Are you sure?'}, :class => "fas fa-trash" %>
                </b>
              </td>
            </tr>
          <% end %>
          
        </table>
      </div>
    </div>

    <div style="display: none;">
      <!-- Table To Save In Excel -->
      <div id="dvData">
        <table>
          <tr>
            <th>SUB-COUNTY</th>
            <th>INVESTITURE</th>
            <th></th>
            <th></th>
            <th></th>
            <th>TOTAL</th>
          </tr>

          <tr>
            <td></td>
            <td><b>Sungura</b></td>
            <td><b>Chipukizi</b></td>
            <td><b>Mwamba</b></td>
            <td><b>Jasiri</b></td>
            <td></td>
          </tr>

          <% @mombasas.each do |mombasa| %>
            <tr style="font-size: 1.2rem;">
              <td><b><%= mombasa.sub_county %></b></td>
              <td><%= mombasa.investiture_sungura %></td>
              <td><%= mombasa.investiture_chipukizi %></td>
              <td><%= mombasa.investiture_mwamba %></td>
              <td><%= mombasa.investiture_jasiri %></td>
              <td><b><%= mombasa.total %></b></td>
            </tr>
          <% end %>
          
        </table>
      </div>
      <!-- Table To Save In PDF -->
      <section style="min-height: calc(90vh - 40px);padding: 80px 40px 100px 40px;" id="dvContainer">
        <div style="background-color: rgba(174, 182, 191, 0.1);border-radius: 10px;width: 95%;margin: auto;padding: 100px 20px 280px 20px;">

          <div style="padding: 0 40px 20px 40px;">
            <h3 style="padding-bottom: 20px;text-align: center;">SUB-COUNTY INVESTITURE</h3>
            
            <div class="table-responsive">
              <table class="table table-hover" style="font-family: arial, sans-serif;border-collapse: collapse;width: 100%;">
                <tr style="font-size: 1.1rem;background-color: #C7CCD1;">
                  <th style="border: 1px solid #85929E;padding: 8px;">SUB-COUNTY</th>
                  <th colspan="4" style="border: 1px solid #85929E;padding: 8px;">INVESTITURE</th>
                  <th style="border: 1px solid #85929E;padding: 8px;">TOTAL</th>
                </tr>
                <tr style="font-size: 1rem;background-color: #ECF0F1;">
                  <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"></td>
                  <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><b>Sungura</b></td>
                  <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><b>Chipukizi</b></td>
                  <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><b>Mwamba</b></td>
                  <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><b>Jasiri</b></td>
                  <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"></td>
                </tr>

                <% @mombasas.each do |mombasa| %>
                  <tr style="font-size: 0.9rem;background-color: #ECF0F1;">
                    <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><b><%= mombasa.sub_county %></b></td>
                    <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><%= mombasa.investiture_sungura %></td>
                    <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><%= mombasa.investiture_chipukizi %></td>
                    <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><%= mombasa.investiture_mwamba %></td>
                    <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><%= mombasa.investiture_jasiri %></td>
                    <td style="border: 1px solid #85929E;padding: 8px;text-align: center;"><b><%= mombasa.total %></b></td>
                  </tr>
                <% end %>
           
              </table>
            </div>
          </div>
        </div>
      </section>
    </div>

    <div style="text-align: right;padding: 20px 40px 20px 0;">
      <a id="btnExport" type="button" class="record-button1">
        <i class="fa-solid fa-file-excel">&ensp;</i>
        <span>Export Excel</span>
      </a>

      <a class="record-button2" id="PrintNow" type="button">
        <i class="fa-solid fa-file-pdf">&ensp;</i>
        <span>Export PDF</span>
      </a>
    </div>
  </div>  
</section>

app/views/mombasas/new.html.erb
<div class="limiter">
  <div class="container-login100" style="padding-top: 160px;padding-bottom: 60px;">
    <div class="wrap-login100">
      <div class="login100-form-title" style="background-image: url(/assets/login-image.png);">
        <span class="login100-form-title-1">
          <b>Add New Record</b>
        </span>
      </div>

      <div style="padding: 10px;">
        <% flash.each do |type, msg| %>
          <%= content_tag :div, msg, class: build_alert_classes(type) %>
        <% end %>
      </div>

      <form class="login100-form validate-form" action="/mombasas" method="post">
        <div class="wrap-input100 validate-input m-b-26" data-validate="Email is required" style="margin-bottom: 20px !important;">
          <span class="label-input100">Sub County</span>
          <input class="input100" type="text" name="mombasa[sub_county]" placeholder="Sub County" autofocus="autofocus" autocomplete="off">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-26" data-validate="Sungura is required" style="margin-bottom: 20px !important;">
          <span class="label-input100">Sungura</span>
          <input class="input100" type="number" name="mombasa[investiture_sungura]" placeholder="Investiture Sungura" autofocus="autofocus" autocomplete="off">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-26" data-validate="Chipukizi is required" style="margin-bottom: 20px !important;">
          <span class="label-input100">Chipukizi</span>
          <input class="input100" type="number" name="mombasa[investiture_chipukizi]" placeholder="Investiture Chipukizi" autofocus="autofocus" autocomplete="off">
          <span class="focus-input100"></span>
        </div>

        <div class="wrap-input100 validate-input m-b-26" data-validate="Mwamba is required" style="margin-bottom: 20px !important;">
          <span class="label-input100">Mwamba</span>
          <input class="input100" type="number" name="mombasa[investiture_mwamba]" placeholder="Investiture Mwamba" autofocus="autofocus" autocomplete="off">
          <span class="focus-input100"></span>
        </div>


        <div class="wrap-input100 validate-input m-b-26" data-validate="Jasiri is required" style="margin-bottom: 20px !important;">
          <span class="label-input100">Jasiri</span>
          <input class="input100" type="number" name="mombasa[investiture_jasiri]" placeholder="Investiture Jasiri" autofocus="autofocus" autocomplete="off">
          <span class="focus-input100"></span>
        </div>

        <div class="container-login100-form-btn" style="margin: 40px 0 40px 0 !important;">
          <button type="submit" class="login100-form-btn">Add New!</button>
        </div>
      </form>

    </div>
  </div>
</div>

app/views/mombasas/show.html.erb
<section style="min-height: calc(90vh - 40px);padding: 180px 40px 100px 40px;">
  <div style="background-color: rgba(174, 182, 191, 0.4);border-radius: 10px;width: 95%;margin: auto;padding: 20px 20px 80px 20px;">
    

    <%# link_to 'Download Pdf', mombasas_path(@mombasa, format: :pdf) %>

    <div style="padding: 50px 0 40px 40px;text-align: left;">
      <a style="border: 4px solid #641E16;color: #641E16;padding: 10px 40px 10px 40px;font-size: 20px;font-weight: bold;" href="/mombasas/new">
        <i class="fa-solid fa-plus">&ensp;</i>
        <span>Add Record</span>
      </a>
    </div>

    <div style="padding: 10px;">
      <% flash.each do |type, msg| %>
        <%= content_tag :div, msg, class: build_alert_classes(type) %>
      <% end %>
    </div>

    <div style="padding: 0 40px 20px 40px;">
      <h2 style="padding-bottom: 20px;">SUB-COUNTY INVESTITURE</h2>
      
      <div class="table-responsive">
        <table class="table table-hover">
          <tr style="font-size: 1.5rem;">
            <th>SUB-COUNTY</th>
            <th colspan="4">INVESTITURE</th>
            <th>TOTAL</th>
          </tr>
          <tr style="font-size: 1.4rem;">
            <td></td>
            <td><b>Sungura</b></td>
            <td><b>Chipukizi</b></td>
            <td><b>Mwamba</b></td>
            <td><b>Jasiri</b></td>
            <td></td>
          </tr>

          <tr style="font-size: 1.2rem;">
            <td><b><%= @mombasa.sub_county %></b></td>
            <td><%= @mombasa.investiture_sungura %></td>
            <td><%= @mombasa.investiture_chipukizi %></td>
            <td><%= @mombasa.investiture_mwamba %></td>
            <td><%= @mombasa.investiture_jasiri %></td>
            <td><b><%= @mombasa.total %></b></td>
          </tr>

          
        </table>
      </div>
    </div>

    <div style="text-align: right;padding: 20px 40px 20px 0;">
      <a style="border: 4px solid #641E16;color: #641E16;padding: 10px 40px 10px 40px;font-size: 20px;font-weight: bold;" href="#">
        <i class="fa-solid fa-plus">&ensp;</i>
        <span>Download Record</span>
      </a>
    </div>
  </div>
</section>